site_name: MoirePy – Python Library for Moiré Lattice Simulation
site_description: "MoirePy is a Python library for bilayer moiré lattice simulations using tight-binding models. Open-source, installable via PyPI."
site_url: https://jabed-umar.github.io/MoirePy/
repo_url: https://github.com/jabed-umar/MoirePy
repo_name: jabed-umar/MoirePy

theme:
  name: material
  logo: assets/logo.svg
  # favicon: images/logo/favicon.png
  features:
    # - navigation.expand
    - navigation.sections

  palette:
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            # This is the single biggest fix for "pretty" parameters
            docstring_section_style: table 
            show_root_heading: false
            show_source: false
            # Separates the function name from its arguments for clarity
            separate_signature: true 
            # Styles 'See Also' and 'Notes' more distinctly
            merge_init_into_class: true
  - bibtex:
      bib_file: docs/refs.bib

extra_css:
  - assets/style.css

# extra_javascript:
#   - assets/script_find_theta.js

extra:
  notebooks_to_convert:
    - getting_started/quickstart_tbg.ipynb
    - getting_started/k_space_hamiltonian.ipynb
    - getting_started/obc_vs_pbc.ipynb
    - getting_started/prepare_layers.ipynb
    - getting_started/custom_hoppings.ipynb


nav:
  - Home: index.md
  - Getting Started:
    - Quickstart TBG in 5 Minutes: getting_started/quickstart_tbg.md
    - K-Space Hamiltonian Generation: getting_started/k_space_hamiltonian.md
    - Simulating Lattices in Open vs. Periodic Boundary Conditions: getting_started/obc_vs_pbc.md
    - Defining Custom Layers: getting_started/prepare_layers.md
    - Designing Custom Hopping: getting_started/custom_hoppings.md
  - Tutorials and Benchmarks:
    - Tutorials and Replicated Papers: examples.md
    - Benchmarks and Performance Tips: benchmarks.md
  - Theory:
    - Theoretical Background: theory/theory_intro.md
    - Tight Binding Formulation: theory/tight_binding_ham.md
    - Searching Algorithm & KDTree: theory/search_algorithm_kdtree.md
    - Angle Calculation Logic: theory/angle_calculation_process.md
    - Angle Value Calculator: theory/avc.md
  - API Reference:
    - Overview: api/index.md
    - Core Classes:
      - Layer: api/generated/moirepy.layers.Layer.md
      - BilayerMoireLattice: api/generated/moirepy.moire.BilayerMoireLattice.md
    - Built-in Layers:
      - SquareLayer: api/generated/moirepy.layers.SquareLayer.md
      - TriangularLayer: api/generated/moirepy.layers.TriangularLayer.md
      - Rhombus60Layer: api/generated/moirepy.layers.Rhombus60Layer.md
      - KagomeLayer: api/generated/moirepy.layers.KagomeLayer.md
      - HexagonalLayer: api/generated/moirepy.layers.HexagonalLayer.md
    - Utilities:
      - get_rotation_matrix: api/generated/moirepy.utils.get_rotation_matrix.md
      - are_coeffs_integers: api/generated/moirepy.utils.are_coeffs_integers.md
      - LatticeAlreadyFinalisedError: api/generated/moirepy.utils.LatticeAlreadyFinalisedError.md

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

hooks:
  - mkdocs_hooks.py
