name: Deploy Docs

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Switch to main branch and Install dependencies
        run: |
          git checkout main
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      # - name: Copy README and populate examples
      #   run: |
      #     cat README.md > docs/index.md
      #     python docs/routine/pop.py

      - name: Deploy with MkDocs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          JUPYTER_PLATFORM_DIRS=1 mkdocs gh-deploy -b docs
